version: '3.8'
services:

  neo4j:
    image: neo4j:4.1.1
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - graph_data_dir:/data
    environment:
      NEO4J_AUTH: neo4j/mangalho

volumes:
  graph_data_dir:
